-- SQL Script untuk membuat tabel orders dan mengaktifkan Realtime

-- 1. Buat tabel orders (jika belum)
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number TEXT NOT NULL,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  order_type TEXT NOT NULL,
  payment_method TEXT NOT NULL,
  total_amount NUMERIC NOT NULL,
  status TEXT DEFAULT 'pending',
  receipt_url TEXT,
  items JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- 2. Policy untuk Orders
DROP POLICY IF EXISTS "Enable insert for anon" ON public.orders;
CREATE POLICY "Enable insert for anon" ON public.orders FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Enable select for everyone" ON public.orders;
CREATE POLICY "Enable select for everyone" ON public.orders FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable update for everyone" ON public.orders;
CREATE POLICY "Enable update for everyone" ON public.orders FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Enable delete for everyone" ON public.orders;
CREATE POLICY "Enable delete for everyone" ON public.orders FOR DELETE USING (true);

-- 3. MENGAKTIFKAN REALTIME UNTUK TABEL PRODUCTS
-- Script ini akan membuat perubahan di tabel products ter-broadcast ke seluruh aplikasi secara live
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND tablename = 'products'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.products;
  END IF;
END;
$$;

-- 4. FUNGSI UNTUK MENGURANGI STOK DENGAN AMAN
CREATE OR REPLACE FUNCTION decrement_product_stock(p_id BIGINT, p_amount INT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE public.products
  SET stock = GREATEST(stock - p_amount, 0)
  WHERE id = p_id;
END;
$$;
